### ISSUE TITLE
Common ground: The beer case

### ISSUE THREAD

**Issue by maxvisser** [teamforus/research-and-development#100]
### Tasks:
 - [ ] Beer case front end
    - [ ] Design @Myshelova 
    - [ ] Build @kremlinwarrior 

The front end (shown at iPad/computer screen at the bar) will show a QR-code. After scanning, you will be asked to share your attribute (18+). When you approve and have the attribute, the screen will turn geen and show your profile picture. Stretch goal: it can also ask you to make the payment trough the me app (in crypto or euro's trough the bunq api) we could simulate this, just to show how it could work, and how it's an advantage of the me app having both your wallet and attributes.

**Comment by jknnr** [comment]
wow the issue #100! congrats

**Comment by jamalv** [comment]
Let’s celebrate with a case of beer! 🍻
