### ISSUE TITLE
Commit vote and me app demo

### ISSUE THREAD

**Issue by jamalv** [teamforus/research-and-development#80]
- [x] commit vote demo @danrminds @dev-weget
- [x] commit me demo @danrminds @dev-weget
- [x] make pull request to https://github.com/TeamSnowflake/research-and-development @jamalv

**Comment by jamalv** [comment]
Added placeholders: https://github.com/teamforus/research-and-development/tree/demos

**Comment by danrminds** [comment]
The designs will also be added in this repository via Git LFS?

**Comment by jamalv** [comment]
Yea, designs as well 👍 LFS should happen automatically I think (hope) or maybe you have to install the software: https://git-lfs.github.com

**Comment by jamalv** [comment]
And I don't know if you still have write access to this repo (@maxvisser?), otherwise you have to fork it, commit it in your own fork (where you will have full access) and then create a pull request to this repository.

**Comment by danrminds** [comment]
I already have LFS installed. Can you please create placeholder folders for the designs?

**Comment by jamalv** [comment]
done 👍
