### ISSUE TITLE
Recompile me demo iOS

### ISSUE THREAD

**Issue by jamalv** [teamforus/research-and-development#82]
https://github.com/teamforus/me/issues/27

**Comment by jamalv** [comment]
@danrminds could you give me your apple-id? I will add you as a developer at the Foundation Forus Apple organisation so Valentin is also able to do this.

**Comment by danrminds** [comment]
d.ghimpu@rminds.nl

**Comment by jamalv** [comment]
invitation sent 👍

**Comment by danrminds** [comment]
We will try to recompile it during tomorrow (Monday)

**Comment by maxvisser** [comment]
What is the status on this issue?

**Comment by jamalv** [comment]
We recompiled the app on my computer, it did not work on Valentin's yet due to a bunch of weird issues. 

Maybe this is not needed anymore since the demo will lose focus to the native app anyway (developed and compiled by Daniel)
