### ISSUE TITLE
Me demo v0.2

### ISSUE THREAD

**Issue by maartenfv** [teamforus/research-and-development#84]
We are currently working on a design update for the me app. It would be good to update the demo and deploy it to the stakeholders.

- [x] finish designs https://github.com/teamforus/me/issues/26 @danrminds @dev-weget 
- [x] translate / update texts @linda-90 
- [x] update the demo @danrminds @dev-weget 
- [ ] deploy demo to stakeholders @gerbenbosschieter

**Comment by danrminds** [comment]
Do you want to spend time now on updating the demo? Or only about using images as demo?
So I know how to plan everything.

**Comment by maartenfv** [comment]
Demo it is.

Timeline:

Finish design:  fr. 11-04 @danrminds 
Text: 11-04 @linda-90 @danrminds Review: @gerbenbosschieter
Dev: fr. 18-04 @danrminds

**Comment by jamalv** [comment]
designs available here (for translation): https://github.com/teamforus/research-and-development/blob/develop/demo002-me/designs/flowchart.png

**Comment by maartenfv** [comment]
Linda is informed, she will translate text in png (link above) and will be notified when the rest of the designs are finished

**Comment by linda-90** [comment]
I have sent the translations to @danrminds

**Comment by danrminds** [comment]
Demo v0.2 developed. Left: to deploy the iOS version via TestFlight. 
@jamalv When would you have some time to sync with Valentin and do it together?

**Comment by maxvisser** [comment]
@GerbenBosschieter What do you still need for me to deploy the new version to the stakeholders?

**Comment by jamalv** [comment]
New demo is in TestFlight and on gerbens phone, when it is tested well we could start deploying to stakeholders. We should make a more concrete plan about this. Since @maartenfv is in contact with the stakeholders I think this falls under his responsibility. 

One concern I have: There still are some issues to fix on the demo, I don't think it is worth the time investment to fix it since hopefully the native apps will start to be demo-able asap. @maartenfv could you share what the value of the demo is to you right now and what strategy you would like to employ on it?

**Comment by maxvisser** [comment]
Yes it probably needs alot more support / work to get the new version rolling organisational. Time investment/strategy on this is for @maartenfv ; @GerbenBosschieter can maybe help contacting all stakeholders though.

**Comment by GerbenBosschieter** [comment]
I can at least start to test the demo properly, not really sure what's in the scope of the functionalities  of the demo is. But nevertheless I will test it like it should work as a completely developed Me-App.
In the meanwhile we can wait till @maartenfv informs us of the value of the demo and I am definitely able to help contacting the stakeholders 👍

**Comment by GerbenBosschieter** [comment]
So I've done some tests on the Demo, I don't know if you guys want me to create issues for results. IF so, pleas tell me :)

Demo v0.2 test

Tab: Records

- [ ] It’s only possible to open the option ‘personal’ , other options can’t be opened.
- [ ] The phone number and BSN number are the same if you open ‘personal’. This can be confusing giving a demo.

Tab: Wallet

- [ ]  Search option doesn’t work.
- [ ]  The tab ‘assets’ is completely empty.
- [ ]  After confirming splitting a voucher you will not get redirected to the vouchers tab. This assumes nothing happened, go to the voucher tab manually and you’ll see it did split.

Tab: Account settings

- [ ] I can’t use the ‘add existing identity’ option , there is no e-mail sent. All the other options work.

Website:

- [ ] It’s not possible to show how kindpakket tokens can be transferred into the wallet by scanning the QR-Code. Nothing happens after scanning the QR-Code.

**Comment by jamalv** [comment]
Thx, @GerbenBosschieter 
@danrminds, me and @maartenfv will discuss how to proceed

**Comment by danrminds** [comment]
Tab assets is empty only for the regular citizens. If you switch to the Zuidhorn identity - you will see their building in the assets.

**Comment by maxvisser** [comment]
@danrminds i would just add the tesla back or maybe add a cryptokitty

**Comment by maartenfv** [comment]
I will place this on the direction agenda for 26-7 and make a final decision. https://docs.google.com/document/d/1h0ZVh7VzMUPJJ3JngRmHElmkFhBhOUKOn9_SwJ67uK4/edit

**Comment by maartenfv** [comment]
Missie gaat door. Er komt een nieuwe versie. Gerben rolt uit. @GerbenBosschieter

**Comment by maartenfv** [comment]
Demo afmaken zo simpel mogelijk. Verder op de echte app.

**Comment by GerbenBosschieter** [comment]
Deployment is done, will not close this issue yet.
The android app apparently isn't working. Valentin is rebuilding it.

**Comment by maartenfv** [comment]
@GerbenBosschieter @jamalv  Wat is de status/jullie kijk op deze issue?

**Comment by jamalv** [comment]
I think most stakeholders have the demo v0.2, so it can be considered as deployed. If other requests come up we can answer them on a case-by-case basis. Now it is just a matter of moving to our native implementations asap :)
