### ISSUE TITLE
Vote demo feedback from apple

### ISSUE THREAD

**Issue by jamalv** [teamforus/research-and-development#87]
From apple:

> Upon further review, we found that your app does not comply with the following guidelines:
> 
> Guideline 4.2.3 - Design - Minimum Functionality
> 
> We were required to install Me before we could use your app. Apps should be able to run on launch, without requiring additional apps to be installed.
> 
> Next Steps
> 
> To resolve this issue, please revise your app to ensure that users can use it upon launch. If your app requires authentication before use, please use methods that can authenticate users from within your app.
> 
> Best Regards,
> 
> TestFlight Beta Review

Suggestion: redesign the [vote demo](https://github.com/teamforus/research-and-development/tree/develop/demo003-vote) so that users are able to access functionality without logging in. When they perform the actual vote, then we can redirect them to the me app. If they don't have the me app we could ask them to download it or maybe register their vote as a "light" vote.

**Comment by maxvisser** [comment]
Maybe outside collaborators can help with this issue?

http://github.com/teamsnowflake/research-and-development

**Comment by maxvisser** [comment]
Has no priority right now. I close this issue until its relevant again. https://github.com/TeamSnowflake/research-and-development/issues/2#issuecomment-393115745
